eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
spring:
  application:
    name: waffle-api
server:
  port: 8081
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
management:
  endpoints:
#    enabled-by-default: true
    web:
      exposure:
        include: '*'
