eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  10000