eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
spring:
  application:
    name: waffle-notification
server:
  port: 8010
logging:
  level:
    -org.springframework.security: debug