eureka:
  instance:
    appname: sso
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
server:
  port: 8083
spring:
  application:
    name: sso
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    database: 0
logging:
  level:
    - org.springframework.security: debug

