eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
spring:
  application:
    name: service-zuul
server:
  port: 8080
zuul:
  ignored-services: '*'
  retryable: true
  routes:
    hi:
      path: /hi
      sensitiveHeaders:
      serviceId: waffle-api
management:
  endpoints:
#    enabled-by-default: true
    web:
      exposure:
        include: '*'




