eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
spring:
  application:
    name: service-zuul
server:
  port: 8080
zuul:
  ignored-services: '*'
  routes:
    hi:
      path: /*
      serviceId: waffle-api


